import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["var(--font-inter)"],
        mono: ["var(--font-mono)"],
      },
      keyframes: {
        flicker: {
          "0%, 100%": { opacity: "1" },
          "31.98%": { opacity: "1" },
          "32%": { opacity: "0" },
          "32.8%": { opacity: "0" },
          "32.82%": { opacity: "1" },
          "34.98%": { opacity: "1" },
          "35%": { opacity: "0" },
          "35.7%": { opacity: "0" },
          "35.72%": { opacity: "1" },
          "36.98%": { opacity: "1" },
          "37%": { opacity: "0" },
          "37.6%": { opacity: "0" },
          "37.62%": { opacity: "1" },
          "67.98%": { opacity: "1" },
          "68%": { opacity: "0" },
          "68.4%": { opacity: "0" },
          "68.42%": { opacity: "1" },
          "95.98%": { opacity: "1" },
          "96%": { opacity: "0" },
          "96.7%": { opacity: "0" },
          "96.72%": { opacity: "1" },
        },
        "glitch-1": {
          "0%, 100%": { transform: "translate(0)" },
          "20%": { transform: "translate(-2px, 2px)" },
          "40%": { transform: "translate(-2px, -2px)" },
          "60%": { transform: "translate(2px, 2px)" },
          "80%": { transform: "translate(2px, -2px)" },
        },
        "glitch-2": {
          "0%, 100%": { transform: "translate(0)" },
          "20%": { transform: "translate(2px, -2px)" },
          "40%": { transform: "translate(2px, 2px)" },
          "60%": { transform: "translate(-2px, -2px)" },
          "80%": { transform: "translate(-2px, 2px)" },
        },
        "glitch-skew": {
          "0%, 100%": { transform: "skew(0)" },
          "10%": { transform: "skew(1deg)" },
          "20%": { transform: "skew(0)" },
          "30%": { transform: "skew(-1deg)" },
          "40%": { transform: "skew(0)" },
          "50%": { transform: "skew(1deg)" },
          "60%": { transform: "skew(0)" },
          "70%": { transform: "skew(-1deg)" },
          "80%": { transform: "skew(0)" },
          "90%": { transform: "skew(1deg)" },
        },
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "bg-glitch-slide": {
          "0%": { backgroundPosition: "0% 0%" },
          "20%": { backgroundPosition: "0% 0%" },
          "21%": { backgroundPosition: "0% 20%" },
          "40%": { backgroundPosition: "0% 20%" },
          "41%": { backgroundPosition: "0% 40%" },
          "60%": { backgroundPosition: "0% 40%" },
          "61%": { backgroundPosition: "0% 60%" },
          "80%": { backgroundPosition: "0% 60%" },
          "81%": { backgroundPosition: "0% 80%" },
          "100%": { backgroundPosition: "0% 80%" },
        },
        "bg-glitch-slide-h": {
          "0%": { backgroundPosition: "0% 0%" },
          "20%": { backgroundPosition: "0% 0%" },
          "21%": { backgroundPosition: "30% 0%" },
          "40%": { backgroundPosition: "30% 0%" },
          "41%": { backgroundPosition: "60% 0%" },
          "60%": { backgroundPosition: "60% 0%" },
          "61%": { backgroundPosition: "90% 0%" },
          "80%": { backgroundPosition: "90% 0%" },
          "81%": { backgroundPosition: "0% 0%" },
          "100%": { backgroundPosition: "0% 0%" },
        },
        "data-corruption": {
          "0%": { opacity: "0.3", transform: "translateX(0)" },
          "5%": { opacity: "0.4", transform: "translateX(-2px)" },
          "10%": { opacity: "0.3", transform: "translateX(0)" },
          "50%": { opacity: "0.6", transform: "translateX(1px)" },
          "100%": { opacity: "0.3", transform: "translateX(0)" },
        },
        "bg-glitch-clip": {
          "0%": { clipPath: "inset(0% 0% 0% 0%)" },
          "20%": { clipPath: "inset(30% 0% 0% 0%)" },
          "40%": { clipPath: "inset(0% 0% 0% 0%)" },
          "60%": { clipPath: "inset(0% 30% 0% 0%)" },
          "80%": { clipPath: "inset(0% 0% 0% 0%)" },
          "100%": { clipPath: "inset(0% 0% 0% 0%)" },
        },
        "glitch-bar": {
          "0%": { transform: "translateY(-50%) scaleY(1)" },
          "50%": { transform: "translateY(-20%) scaleY(0.6)" },
          "100%": { transform: "translateY(-50%) scaleY(1)" },
        },
        "glitch-bar-v": {
          "0%": { transform: "translateX(0) scaleX(1)" },
          "50%": { transform: "translateX(20%) scaleX(0.6)" },
          "100%": { transform: "translateX(0) scaleX(1)" },
        },
      },
      animation: {
        flicker: "flicker 4s linear infinite",
        "glitch-1": "glitch-1 5s linear infinite alternate",
        "glitch-2": "glitch-2 5s linear infinite alternate",
        "glitch-skew": "glitch-skew 3s linear infinite alternate",
        blink: "blink 1s steps(1) infinite",
        "bg-glitch-slide": "bg-glitch-slide 8s steps(1) infinite",
        "bg-glitch-slide-h": "bg-glitch-slide-h 7s steps(1) infinite",
        "data-corruption": "data-corruption 4s ease-in-out infinite",
        "bg-glitch-clip": "bg-glitch-clip 10s steps(1) infinite",
        "glitch-bar": "glitch-bar 6s ease infinite alternate",
        "glitch-bar-v": "glitch-bar-v 7s ease infinite alternate",
      },
      transformStyle: {
        "3d": "preserve-3d",
      },
      perspective: {
        "800": "800px",
        "1000": "1000px",
      },
      translate: {
        "z-0": "0px",
        "z-1": "1px",
        "z-2": "2px",
        "z-3": "3px",
        "z-4": "4px",
        "z-8": "8px",
        "z-12": "12px",
      },
    },
  },
  plugins: [],
}

export default config
